version: "3"
services:
  #PHP Service
  api:
    build:
      context: ../api/production
      dockerfile: Dockerfile
    image: keptey/php-7.2
    container_name: api
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: api
      SERVICE_TAGS: prod
    working_dir: /var/www
    volumes:
      - ../api/production:/var/www/api/production
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - 9000:9000
    networks:
      - app-network

  #PHP Service
  devapi:
    build:
      context: ../api/develop
      dockerfile: Dockerfile
    image: keptey/php-7.2
    container_name: devapi
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: devapi
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ../api/develop:/var/www/api/develop
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - 9001:9001
    networks:
      - app-network

  #PHP Service
  stageapi:
    build:
      context: ../api/staging
      dockerfile: Dockerfile
    image: keptey/php-7.2
    container_name: stageapi
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: stageapi
      SERVICE_TAGS: stage
    working_dir: /var/www/api/staging
    volumes:
      - ../api/staging:/var/www/api/staging
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - 9002:9002
    networks:
      - app-network

  #Nginx Service
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: nginx:ubuntu
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
      - "4430:443"
    extra_hosts:
     - "api.keptey.in:192.168.0.49"
     - "devapi.keptey.in:192.168.0.49"
     - "stageapi.keptey.in:192.168.0.49"
    links:
        - api
        - devapi
        - stageapi
    #volumes:
      #- ../api/staging:/var/www/api/staging
      #- ../api/develop:/var/www/api/develop
      #- ../api/production:/var/www/api/production
      #- ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: 123456
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
